### ISSUE TITLE
deepseek 有通用对话和代码助手两个选项，我发现回答的差别有点大

### ISSUE THREAD

**Issue by Jesn** [LLM-Red-Team/deepseek-free-api#1]
deepseek 有通用对话和代码助手两个选项，我发现回答的差别有点大，是否可以提供参数来区别调用那个服务

![image](https://github.com/LLM-Red-Team/deepseek-free-api/assets/5728274/514e39b6-9023-4117-8c91-8d6e98b0b9fe)

![image](https://github.com/LLM-Red-Team/deepseek-free-api/assets/5728274/aa9f25b7-6ea3-4d81-9fb5-cb65e2488e05)

**Comment by Vinlic** [comment]
请见文档
deepseek_chat 通用对话V2
deepseek_code 代码助手
