### ISSUE TITLE
多轮对话拼接bug

### ISSUE THREAD

**Issue by kknd222** [LLM-Red-Team/deepseek-free-api#11]
![PixPin_2024-07-17_17-51-10](https://github.com/user-attachments/assets/8aaf1f83-7e17-4dce-b654-5ef4ff6299d9)
就类似这样
出现user:
assistant:
这样的多轮对话拼接，影响了LLM的回复，现发现问题是影响code修改代码，
比如第一次回复了一个代码，第二次请求告知其哪里哪里有问题，第二次回应时说修改了，实际并没有，代码原封不动的返还回来了。

**Comment by Vinlic** [comment]
为了隔离不同会话的上下文，不会共用你账号的整个会话避免污染，会在每次消息提供完整上下文，这是目前无法避免的问题，你可以考虑减少上下文轮次减少幻觉，像你提到的代码修改问题，一般是模型本身幻觉导致以为自己改过代码了。
