### ISSUE TITLE
[Request Blocked]  Is there a new update strategy to deal with this detection?

### ISSUE THREAD

**Issue by gotoolkits** [LLM-Red-Team/deepseek-free-api#21]
1|deepseek-free-api  | 
1|deepseek-free-api  | [2024-11-18 21:08:38.806][error][chat.ts<273,14>] Invalid response Content-Type: text/html; charset=utf-8
1|deepseek-free-api  | [2024-11-18 21:08:38.810][info][server.ts<66,36>] <- POST /v1/chat/completions 836ms
1|deepseek-free-api  | [2024-11-18 21:08:38.812][error][chat.ts<277,47>] <!DOCTYPE html>
1|deepseek-free-api  | <html lang="en">
1|deepseek-free-api  | <head>
1|deepseek-free-api  |     <meta charset="UTF-8">
1|deepseek-free-api  |     <meta name="viewport" content="width=device-width, initial-scale=1.0">
1|deepseek-free-api  |     <title>Error - Request Blocked</title>
1|deepseek-free-api  |     <style>
1|deepseek-free-api  |         body {
1|deepseek-free-api  |             font-family: 'Arial', sans-serif;
1|deepseek-free-api  |             background-color: #f3f7f9;
1|deepseek-free-api  |             margin: 0;
1|deepseek-free-api  |             padding: 0;
1|deepseek-free-api  |             height: 100vh;
1|deepseek-free-api  |             display: flex;
1|deepseek-free-api  |             justify-content: center;
1|deepseek-free-api  |             align-items: center;
1|deepseek-free-api  |             color: #333;
1|deepseek-free-api  |         }
1|deepseek-free-api  |         .container {
1|deepseek-free-api  |             text-align: center;
1|deepseek-free-api  |             background-color: #ffffff;
1|deepseek-free-api  |             padding: 40px;
1|deepseek-free-api  |             border-radius: 12px;
1|deepseek-free-api  |             box-shadow: 0 6px 20px rgba(0, 0, 0, 0.12);
1|deepseek-free-api  |             max-width: 500px;
1|deepseek-free-api  |         }
1|deepseek-free-api  |         h1 {
1|deepseek-free-api  |             font-size: 28px;
1|deepseek-free-api  |             color: #e74c3c;
1|deepseek-free-api  |             margin-bottom: 20px;
1|deepseek-free-api  |         }
1|deepseek-free-api  |         p {
1|deepseek-free-api  |             font-size: 16px;
1|deepseek-free-api  |             margin: 10px 0;
1|deepseek-free-api  |             color: #555;
1|deepseek-free-api  |         }
1|deepseek-free-api  |         p.event-id {
1|deepseek-free-api  |             font-size: 14px;
1|deepseek-free-api  |             color: #888;
1|deepseek-free-api  |             font-style: italic;
1|deepseek-free-api  |             margin-top: 0;
1|deepseek-free-api  |         }
1|deepseek-free-api  |         a {
1|deepseek-free-api  |             color: #3A82F7;
1|deepseek-free-api  |             text-decoration: none;
1|deepseek-free-api  |         }
1|deepseek-free-api  |         a:hover {
1|deepseek-free-api  |             text-decoration: underline;
1|deepseek-free-api  |         }
1|deepseek-free-api  |         .button {
1|deepseek-free-api  |             display: inline-block;
1|deepseek-free-api  |             margin-top: 20px;
1|deepseek-free-api  |             padding: 10px 20px;
1|deepseek-free-api  |             border-radius: 5px;
1|deepseek-free-api  |             background-color: #3A82F7;
1|deepseek-free-api  |             color: white;
1|deepseek-free-api  |             text-decoration: none;
1|deepseek-free-api  |             font-weight: bold;
1|deepseek-free-api  |             transition: background-color 0.3s ease;
1|deepseek-free-api  |         }
1|deepseek-free-api  |         .button:hover {
1|deepseek-free-api  |             background-color: #3A82F7;
1|deepseek-free-api  |         }
1|deepseek-free-api  |     </style>
1|deepseek-free-api  | </head>
1|deepseek-free-api  | <body>
1|deepseek-free-api  |     <div class="container">
1|deepseek-free-api  |         <p class="event-id">Event ID: 30-inst-179-20241118210838-f69b7ea6</p>
1|deepseek-free-api  |         <h1>Request Blocked</h1>
1|deepseek-free-api  |         <p>This request has been blocked due to a violation of the terms of use.</p>
1|deepseek-free-api  |         <p>If needed, please contact us via email and include the Event ID mentioned above.</p>
1|deepseek-free-api  |         <p><a href="mailto:service@deepseek.com">service@deepseek.com</a></p>
1|deepseek-free-api  |         <a class="button" href="https://www.deepseek.com/">Visit the Official Deepseek Website</a>
1|deepseek-free-api  |     </div>
1|deepseek-free-api  | </body>
1|deepseek-free-api  | </html>
1|deepseek-free-api  |

**Comment by Vinlic** [comment]
Try version 0.0.8.
