### ISSUE TITLE
模型能力显著强于 GPT-3.5

### ISSUE THREAD

**Issue by soloice** [LLM-Red-Team/deepseek-free-api#3]
根据我们自己以及首批用户的测试，模型能力显著强于 GPT-3.5，应该是 GPT-4 的水平。建议修改措辞为 【GPT-4 平替】。

另：以上并非自嗨或者拉踩，其实国内头部大模型（至少在中文领域）都已经明显超过 3.5 的了，友商也都做得很好。只是对普通用户或者不做基座模型的研究者不太关心这方面而已。

**Comment by Vinlic** [comment]
能否提供评测方法与评测结果呢？

**Comment by soloice** [comment]
论文里都有，谢谢。

**Comment by soloice** [comment]
当然我理解你们的顾虑，不想做标题党。如果不愿意提 GPT-4，那么至少希望换成【GPT-3.5 高替】。

**Comment by Vinlic** [comment]
好的，我会采纳这个建议。

**Comment by Vinlic** [comment]
@soloice 
在多方调研后，确定中文能力可达到GPT4水平，已更新简介和文档站点，感谢反馈。
