### ISSUE TITLE
The information returned by the service differs from that returned by DeepSeek

### ISSUE THREAD

**Issue by tjlcast** [LLM-Red-Team/deepseek-free-api#5]
Hello

When I requested the completion interface provided by the *deepseek-free-api*, I encountered the following bad case.

The information returned by the service differs from that returned by DeepSeek, as if individual characters may fail to be parsed.

A specific curl body below:
```json
{
  "model": "deepseek-chat",
  "stream": false,
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant."
    },
    {
      "role": "user",
      "content": "Hello! please give a sql about TOP10 product. Only resposne sql"
    }
  ]
}
```

*deepseek-free-api* returns
<img width="969" alt="image" src="https://github.com/LLM-Red-Team/deepseek-free-api/assets/16621867/4de4a64f-0c94-48ad-9121-900267a23ac1">

*deepseek-api* returns
<img width="982" alt="image" src="https://github.com/LLM-Red-Team/deepseek-free-api/assets/16621867/c26613dd-974e-41b2-b73b-d7ebf24099cc">

I think the blank from `LIMIT 10` is missing in *deepseek-free-api*

**Comment by Vinlic** [comment]
Okay, today I will check this.

**Comment by wolfsilver** [comment]
https://github.com/LLM-Red-Team/deepseek-free-api/blob/eae48d3fa6844b4af1fb8dcb91ef250c483563cc/src/api/controllers/chat.ts#L468-L469

这里把空字符串过滤掉了 

![image](https://github.com/LLM-Red-Team/deepseek-free-api/assets/2452450/6a7825bb-b2b8-4d10-912a-9c2a18b318f5)

**Comment by Vinlic** [comment]
@wolfsilver 我最近没时间处理问题，可否发一个PR
