### ISSUE TITLE
刚进入这个项目，发现已经失效

### ISSUE THREAD

**Issue by wwdmy123** [LLM-Red-Team/deepseek-free-api#6]
请问这个项目已经停止维护了吗

**Comment by Vinlic** [comment]
正常维护，检查你的token

**Comment by wwdmy123** [comment]
tokens已经不行了，网页刷新一次tokens就变了

**Comment by wwdmy123** [comment]
> 正常维护，检查你的令牌

tokens已经不行了，网页刷新一次tokens就变了

**Comment by wwdmy123** [comment]
> 正常维护，检查你的令牌

令牌已经不行了，网页刷新一次令牌就变了
