### ISSUE TITLE
关于令牌

### ISSUE THREAD

**Issue by wwdmy123** [LLM-Red-Team/deepseek-free-api#7]
你好大佬，这个令牌现在是动态的，网页刷新令牌就变了。已经没法用了

**Comment by Vinlic** [comment]
这两天会进行修复

**Comment by wwdmy123** [comment]
> 这两天会进行修复

好的大佬

**Comment by Vinlic** [comment]
@wwdmy123 我这边检查了一下，确认令牌变动不受影响

**Comment by wwdmy123** [comment]
> @wwdmy123 我这边检查了一下，确认令牌变动不受影响

@Vinlic 应该是IP被官方封了。谢谢
