### ISSUE TITLE
多账号接入问题

### ISSUE THREAD

**Issue by xiaozhang959** [LLM-Red-Team/deepseek-free-api#8]
佬，我看readme里面写了：

# 多账号接入

目前同个账号同时只能有一路输出，你可以通过提供多个账号的userToken value并使用,拼接提供：

Authorization: Bearer TOKEN1,TOKEN2,TOKEN3

每次请求服务会从中挑选一个。

但是我实际测试下来似乎没有发现这个限制，是有优化了嘛，我测试两个客户端同时请求，似乎是可以同时回答的

**Comment by Vinlic** [comment]
并发实际上没有限制，这里指的是在上下文层面的一路，你可以开着网页的对话然后用free api发一次请求，会发现它实时的刷新在页面上，也就是对于单个账号来说他们其实是共享一个上下文的，多账号是为了隔离上下文，
